import { build, context } from 'esbuild';

export const options = {
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  outfile: 'main.js',
  sourcemap: false,
  treeShaking: true,
  legalComments: 'inline',
  banner: { js: '/* Generated from src/main.ts by npm run build. Do not edit this file. */' }
};

if (process.argv.includes('--watch')) {
  const buildContext = await context(options);
  await buildContext.watch();
} else if (process.argv[1]?.endsWith('esbuild.config.mjs')) {
  await build(options);
}
