import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const lock = JSON.parse(readFileSync('package-lock.json', 'utf8'));
const sections = ['Third-party notices for the Markdown parser and its runtime dependencies.\nGenerated by node scripts/licenses.mjs.\n\nObsidian is provided by the host and is not bundled.'];
for (const [directory, info] of Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b))) {
  if (!directory || info.dev || info.optional) continue;
  const pkg = JSON.parse(readFileSync(join(directory, 'package.json'), 'utf8'));
  const license = readdirSync(directory).find(name => /^licen[sc]e(?:[.-].*)?$/i.test(name));
  if (!license) throw new Error(`Missing license text for ${pkg.name}`);
  sections.push(`${pkg.name} ${pkg.version}\n${'='.repeat(60)}\n${readFileSync(join(directory, license), 'utf8').trim()}`);
}
writeFileSync('THIRD_PARTY_NOTICES.txt', sections.join('\n\n') + '\n');
